//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madison.ResWare.Service.EstimateFeesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstimateFeesResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EstimateFeesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Madison.ResWare.Service.EstimateFeesService.HUDFees> HUDFeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Madison.ResWare.Service.EstimateFeesService.HUDFees> HUDFees {
            get {
                return this.HUDFeesField;
            }
            set {
                if ((object.ReferenceEquals(this.HUDFeesField, value) != true)) {
                    this.HUDFeesField = value;
                    this.RaisePropertyChanged("HUDFees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HUDFees", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class HUDFees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HUDLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HUDLineDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HUDLine {
            get {
                return this.HUDLineField;
            }
            set {
                if ((object.ReferenceEquals(this.HUDLineField, value) != true)) {
                    this.HUDLineField = value;
                    this.RaisePropertyChanged("HUDLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HUDLineDescription {
            get {
                return this.HUDLineDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.HUDLineDescriptionField, value) != true)) {
                    this.HUDLineDescriptionField = value;
                    this.RaisePropertyChanged("HUDLineDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstimateFeesService.IEstimateFeesService")]
    public interface IEstimateFeesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstimateFeesService/EstimateFees", ReplyAction="http://tempuri.org/IEstimateFeesService/EstimateFeesResponse")]
        Madison.ResWare.Service.EstimateFeesService.EstimateFeesResponse EstimateFees(int theClientID, int theOfficeID, int theTransactionTypeID, int theProductTypeID, string theCity, string theCounty, string theState, decimal theLoanAmount, decimal theSalesPrice, decimal theOriginalDebtAmount, decimal theUnpaidPrincipalAmount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstimateFeesServiceChannel : Madison.ResWare.Service.EstimateFeesService.IEstimateFeesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstimateFeesServiceClient : System.ServiceModel.ClientBase<Madison.ResWare.Service.EstimateFeesService.IEstimateFeesService>, Madison.ResWare.Service.EstimateFeesService.IEstimateFeesService {
        
        public EstimateFeesServiceClient() {
        }
        
        public EstimateFeesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstimateFeesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstimateFeesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstimateFeesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Madison.ResWare.Service.EstimateFeesService.EstimateFeesResponse EstimateFees(int theClientID, int theOfficeID, int theTransactionTypeID, int theProductTypeID, string theCity, string theCounty, string theState, decimal theLoanAmount, decimal theSalesPrice, decimal theOriginalDebtAmount, decimal theUnpaidPrincipalAmount) {
            return base.Channel.EstimateFees(theClientID, theOfficeID, theTransactionTypeID, theProductTypeID, theCity, theCounty, theState, theLoanAmount, theSalesPrice, theOriginalDebtAmount, theUnpaidPrincipalAmount);
        }
    }
}
