// <auto-generated />
namespace Madison.Internal.QM.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class transactiontype_reswarefields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transactiontype_reswarefields));
        
        string IMigrationMetadata.Id
        {
            get { return "201307011613056_transactiontype_reswarefields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
