// <auto-generated />
namespace Madison.Internal.QM.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewTransactionFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTransactionFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201306170350311_NewTransactionFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
