// <auto-generated />
namespace Madison.Internal.QM.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class workflowchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workflowchange));
        
        string IMigrationMetadata.Id
        {
            get { return "201306190149513_workflowchange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
